### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by mwakerman** [Doist/todoist-quickadd#1]
Hi @amix,

I'm excited by this project and hope that it's the first of many such endeavours that will allow for a deeper integration between other web-applications and Todoist.

Something similar to this that would be great is a task viewer URL that would render the 'full task view' that you see when click on a task in the Todoist app. This would allow the task to be viewed/updated without needing to open/redirect users to another tab (e.g. https://todoist.com/app/#task/4405593025).

Feel free to close out this issue and thanks for the effort to launch this project.

**Comment by amix** [comment]
Thanks for the feedback, @mwakerman

> Something similar to this that would be great is a task viewer URL that would render the 'full task view' that you see when click on a task in the Todoist app. This would allow the task to be viewed/updated without needing to open/redirect users to another tab (e.g. https://todoist.com/app/#task/4405593025).

We will at some point make it possible to embed a Todoist task/project somewhere else, but this won't be part of the todoist-quickadd 👍
